Kadai 06
ryo1443/mobile_Ryo pull request #6
Opened 2020-06-04 15:05 UTC by ryo1443

Activityからfragmentの呼び出しは出来たんですけど、トランジションのremoveを使って同じボタンから元に戻そうと思って、試行錯誤繰り返したんですが出来なくて詰みました…具体的な場所でコメントを残します

2020-06-04 15:18 UTC, ryo1443 commented on kadai_06/app/src/main/java/com/e/kadai_06/MainActivity.kt
>                  fragmentTransaction.commit()
この部分で、removeすればフラグメントのビューが消えると思ったんですけど、上手くいきませんでした…hideにしたりしても何も起こらなかったので、変な誤解してると思います…

2020-06-06 00:59 UTC, mcz9mm commented on kadai_06/app/src/main/java/com/e/kadai_06/MainActivity.kt
>                  fragmentTransaction.commit()
AddしたやつはPopBackStackを使うと良いよ。

https://developer.android.com/reference/android/app/FragmentManager.html#popBackStack()

2020-06-06 01:00 UTC, mcz9mm commented on kadai_06/app/src/main/java/com/e/kadai_06/MainActivity.kt
>                  fragmentTransaction.commit()
ちなみにAndroidはiOSと違い戻るボタンがあるからそれでも戻れるよ。
(実機側の戻るボタンで戻れないようにもできる)

2020-06-06 01:15 UTC, mcz9mm commented on kadai_06/app/src/main/java/com/e/kadai_06/MainActivity.kt
>                  fragmentTransaction.commit()
ただPopBackStackだと最後に追加されたのから取り除くだけになってしまうので、明示的にこのFragmentを削除したいって時はRyo君が実装したやつが正解かな。
ちょっと惜しいのでヒント

"test"でタグつけたFragmentを取得できるのでそれを使ってみて。
```
fragmentManager.findFragmentByTag("test")
```

ちなみに、これだとaddした時のインスタンスと違うものなんだよね。
クラスは一緒だけど実態は違うから消せてない。
```
remove(FragmentActivity())
```

2020-06-06 04:29 UTC, ryo1443 commented on kadai_06/app/src/main/java/com/e/kadai_06/MainActivity.kt
>                  fragmentTransaction.commit()
ありがとうございます！試してみます！

2020-06-06 04:40 UTC, ryo1443 commented
どちらの方法でも戻れるように改善しました！

2020-06-06 04:54 UTC, mcz9mm requested changes
一点だけー！！！

2020-06-06 04:54 UTC, mcz9mm commented on kadai_06/app/src/main/java/com/e/kadai_06/MainActivity.kt
> +//                fragmentTransaction.remove(fragmentManager.findFragmentByTag("test")!!)
超細かいけど、!!よりnullチェックをした方が綺麗かな🥶

2020-06-06 06:30 UTC, merged