Kadai 07
ryo1443/mobile_Ryo pull request #7
Opened 2020-06-09 09:00 UTC by ryo1443

MainActivityからfragmentへの値渡しが失敗して詰まりました…コメントで該当する場所を示します。

2020-06-09 09:06 UTC, ryo1443 commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
> +            fragmentTransaction.commit()
ここで、bundleからfragmentにクリックした記事のurlを渡そうと試みてました…
デバッグしたところ、urlはMainAdapterから取得出来てました。

2020-06-09 09:07 UTC, ryo1443 commented on kadai_07/app/src/main/java/com/e/kadai_07/WebViewFragment.kt
> +    }
この部分でurlを取得して、webviewに表示させるつもりでした…

2020-06-09 09:39 UTC, mcz9mm reviewed
コメントしました！

2020-06-09 09:39 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
> +            fragmentTransaction.commit()
惜しい！
ここで渡してる実態はなんだろう？
`fragment`と`WebViewFragment()`は同じインスタンスかな？

https://github.com/ryo1443/mobile_Ryo/pull/7/files#diff-854ef7782339c8dc60fce9035456adf8R54

2020-06-09 09:39 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/WebViewFragment.kt
> +    }
ここの処理自体はオッケーよ

2020-06-09 14:41 UTC, ryo1443 commented
値を渡す箇所は上手く修正出来ました！ただ、新たに問題が生じたので、該当の箇所にメモを残します。

2020-06-09 14:51 UTC, ryo1443 commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
>              fragmentTransaction.commit()
`recyclerview`から呼び出した`fragment`にアニメーションを設定する過程です。
`setCustomAnimations`の後ろ二つの引数で戻るボタンを押したときにもアニメーションが適用されると思ったんですが、上手くいきません…具体的には、戻るボタンを押した瞬間に`fragment`が消えます…泣

2020-06-10 01:37 UTC, mcz9mm reviewed
俺の方だとうまくできてるよ、
webViewなのか戻る時たまにカクツクけど😷

![Jun-10-2020 10-29-30](https://user-images.githubusercontent.com/11751495/84216936-d41bcf80-ab05-11ea-971e-5f0899d76d5a.gif)



ハッキリ確認するのであれば、

スライドアニメーションのtoやfromの値を50%じゃなくてview全体の100%にするのと、
Alphaを1.0のままにしてみるとわかりすいよ。

2020-06-10 01:37 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
>              fragmentTransaction.commit()
第3,4引数に設定できているのでここの実装はあってるね

2020-06-10 01:41 UTC, ryo1443 commented
良かったです！ありがとうございます！

2020-06-10 02:57 UTC, mcz9mm requested changes
コメントしました！

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
> +class CustomViewHolder(val view: View, var articleUrl: HomeFeed? = null): RecyclerView.ViewHolder(view) {
ViewHolderにはRecyclerViewで使うアイテムの中身を保持するだけの役割にして、
そいつ自体のviewの`setOnClickListener `は`MainAdapter`側に任せるイメージかな。

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
> +    init {
ここではアイテムの宣言だけする(initは初期処理が必要であれば書く)

```
class CustomViewHolder(val view: View): RecyclerView.ViewHolder(view) {

    val hoge: TextView = view.textView_hoge
    val fuga: TextView = view.textView_fuga
}
```


そうすると、adapter側で
```
override fun onBindViewHolder(holder: CustomViewHolder, position: Int) {
    // holder.hoge
    // holder.fuga
}
```
みたいに使えるよ

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
> +            val fragmentManager = (view.context as FragmentActivity).supportFragmentManager
RecyclerViewの役割は、データの表示、管理だよね。あくまでリストの表示を任されてるイメージ。
ここでの処理はRecyclerViewを使ってる側で担当するべき処理だと思う！
`Activity`もしくは`Fragment`だけど今回は`Activity`かな。

まずはAdapterでViewのタップ時のListenerを設定できるので、その通知をActivity側で受け取れるようにしよう。

調べた感じここの記事を参考にすると良いはず

https://qiita.com/YS-BETA/items/f54bed772d502c5c06f0#%E3%83%AA%E3%82%B9%E3%83%8A%E3%83%BC%E3%82%92%E4%BD%9C%E3%82%8B

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): CustomViewHolder {
Good

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
> +    override fun getItemCount(): Int {
Good

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainAdapter.kt
> +        holder.view.textView_article_title.text = article.title
ここはCustomViewHolderが直ればもっとスッキリ描けるようになるね

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/WebViewFragment.kt
> +
不要な改行は消しちゃおう

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainActivity.kt
> +        AnimationUtils.loadAnimation(this, R.anim.slide_in_right)
Tips:
こいつは実際なくても動くよ！
(読み込みに時間かかって動かないのであれば予め読み込んでも大丈夫)

2020-06-10 02:57 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainActivity.kt
> +                runOnUiThread{
メインスレッド更新Good

2020-06-10 04:40 UTC, ryo1443 commented
参考になります！また修正して提出します

2020-06-10 15:59 UTC, ryo1443 commented
Adapterでのタップ時の通知をActivityに伝える過程で、詰まってしまいました…
具体的な箇所で説明します

2020-06-10 16:22 UTC, ryo1443 commented on kadai_07/app/src/main/java/com/e/kadai_07/MainActivity.kt
> +                }
この箇所で、homeFeedを渡してアダプターをセットしてから、同じようにhomeFeedを渡してクリックリスナーを起動させようとしたのですが、その過程で`lateinit property listener has not been initialized`というエラーが出ました。この原因を色々考えて、apiコールの外側で実行させようと試みたのですがそれも上手くいきません。

2020-06-10 16:24 UTC, ryo1443 commented on kadai_07/app/src/main/java/com/e/kadai_07/MainActivity.kt
> +        }
具体的には、companion objectでapiコールの中からhomeFeedを抽出して、ここのコードのように実行させようとしてました。アドバイスお願いします！

2020-06-11 02:02 UTC, mcz9mm reviewed
コメントしました！

2020-06-11 02:02 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainActivity.kt
> +//                    fragment_recyclerview.adapter = MainAdapter(it)}
Adapterクラスを何度も生成してるように見えるね。

https://github.com/ryo1443/mobile_Ryo/pull/7/files#diff-84865d85193559aee926686f44590271R52

課題で何回か触れたけどインスタンスへの理解を深めてみるとわかると思うよ。

ここで入れようとしてるMainAdapterをAとして、
```
fragment_recyclerview.adapter = MainAdapter(it)　//A
```

さらにここで再度adapterをセットしてます。(既に2回セットし直してる)
同じMainAdapterだけど内部的には別物のMainAdapter(B)が再度セットされてる

https://github.com/ryo1443/mobile_Ryo/pull/7/files#diff-84865d85193559aee926686f44590271R52
```
fragment_recyclerview.adapter = MainAdapter(it)  //B
```

3回目に出てくる`MainAdapter(C)`は生成したやつをそのまま使って`setOnItemClickListener`を呼び出そうとしてるね。
https://github.com/ryo1443/mobile_Ryo/pull/7/files#diff-84865d85193559aee926686f44590271R54

```
MainAdapter(it).setOnItemClickListener(object : MainAdapter.OnItemClickListener {
```

同じ`MainAdapter`でも`fragment_recyclerview`にセットされてるadapterが利用されてないのに注目してみるとわかりやすいかな。

2020-06-11 02:02 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainActivity.kt
> +            MainAdapter(it).setOnItemClickListener(object : MainAdapter.OnItemClickListener {
先日貼った[記事](https://qiita.com/YS-BETA/items/f54bed772d502c5c06f0#%E3%83%AA%E3%82%B9%E3%83%8A%E3%83%BC%E3%82%92%E4%BD%9C%E3%82%8B)を見てみると違いがわかるかと。

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val list = Array<String>(10) {"テキスト$it"}
        val adapter = CustomAdapter(list) //  ここでCustomAdapterを生成-①
        val layoutManager = LinearLayoutManager(this )

        simpleRecyclerView.layoutManager = layoutManager
        simpleRecyclerView.adapter = adapter // ①で生成したadaptereをセット
        simpleRecyclerView.setHasFixedSize(true)

        // ①で生成したadaptereのsetOnItemClickListenerの呼び出し
        adapter.setOnItemClickListener(object:CustomAdapter.OnItemClickListener{
            override fun onItemClickListener(view: View, position: Int, clickedText: String) {
                Toast.makeText(applicationContext, "${clickedText}がタップされました", Toast.LENGTH_LONG).show()
            }
        })
    }
```

2020-06-11 02:02 UTC, mcz9mm commented on kadai_07/app/src/main/java/com/e/kadai_07/MainActivity.kt
> +            MainAdapter(it).setOnItemClickListener(object : MainAdapter.OnItemClickListener {
Hint

MainActivityのクラスプロパティにadapterを用意してあげればonCreate以外でも使えるよ。
```
class MainActivity : AppCompatActivity() {

    companion object {
        var homeFeed2 : Array<HomeFeed>? = null
    }

    var adapter: MainAdapter? = null
```

2020-06-11 14:56 UTC, ryo1443 commented
ありがとうございます！ほぼ記事通り模倣したらエラー吐くことなくなりました…感謝です

2020-06-11 15:04 UTC, ryo1443 commented
一通り修正しきったので、お願いします

2020-06-12 02:20 UTC, mcz9mm commented
LTGM お疲れ様！
![](https://media.giphy.com/media/3oEdv9HWXUUUd44Cc0/giphy.gif)

2020-06-12 03:51 UTC, ryo1443 commented
ありがとうございます！

2020-06-12 03:51 UTC, merged